In [ ]:
# 4. Instalar a bibliotecas pandas
!pip install -q pandas

In [9]:
import random, time
import pandas as pd

def coletar_dados(sensores=1000, leituras_por_sensor=100):
    dados = []
    for s in range(sensores):
        for l in range(leituras_por_sensor):
            leitura = {
                'sensor_id': s,
                'temperatura': round(random.uniform(20.0, 80.0), 2),
                'vibracao': round(random.uniform(0.1, 5.0), 2),
                'corrente': round(random.uniform(0.5, 10.0), 2),
                'timestamp': time.time()
            }
            dados.append(leitura)
    return pd.DataFrame(dados)

df = coletar_dados()
df.head()

   sensor_id  temperatura  vibracao  corrente     timestamp
0          0        56.20      3.57      0.79  1.776277e+09
1          0        63.42      1.73      0.83  1.776277e+09
2          0        33.25      1.04      1.69  1.776277e+09
3          0        21.44      3.52      9.82  1.776277e+09
4          0        57.59      1.39      3.20  1.776277e+09

Esse código simula uma operação industrial de coleta massiva.

### 4.8 Extração de features com pandas (janelas de 1 min)

In [10]:
import pandas as pd

df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s')
df = df.set_index('timestamp')

# agregação por janelas móveis
features = df.groupby('sensor_id').resample('1T').agg({
    'temperatura': ['mean', 'std', 'max'],
    'vibracao': ['mean', 'max']
}).reset_index()

features.head()

/tmp/ipykernel_3551/2865221614.py:7: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  features = df.groupby('sensor_id').resample('1T').agg({

  sensor_id           timestamp temperatura                   vibracao
                                       mean        std    max     mean   max
0         0 2026-04-15 18:14:00     48.1390  17.831553  78.97   2.4431  4.90
1         1 2026-04-15 18:14:00     49.8419  18.058264  79.64   2.5840  4.99
2         2 2026-04-15 18:14:00     48.6494  17.672890  78.86   2.8148  4.99
3         3 2026-04-15 18:14:00     51.3812  16.807362  79.46   2.4949  4.89
4         4 2026-04-15 18:14:00     52.6631  17.969466  79.87   2.6606  4.97